### ISSUE TITLE
apt-fast not working properly with apt

### ISSUE THREAD

**Issue by AgnishRoy** [ilikenwf/apt-fast#178] opened 2020-04-26 07:31 UTC
"Change package manager used for installation. Supported are apt-get, aptitude, apt." 
- I tried it with apt in my Mint 19.3 installation.
If I run _# apt-fast install <package_name>_  - it's giving an error with the following message:

>  Working... this may take a while.
> Package manager quit with exit code.

If I run a generalized command e.g. _# apt-fast update_ - it's showing a list of all available _apt_ options and exiting. 
**N.B.: No such issue faced when tried with _apt-get_**

**Comment by Lasall** [comment] 2020-04-26 15:47
Thank you for reporting this issue. How did you install apt-fast?

**Comment by Lasall** [comment] 2020-04-26 15:51
What is the output of `type apt`? Do you use special options with apt? I currently don't have any ideas why you encounter this problem.

**Comment by AgnishRoy** [comment] 2020-05-09 15:22
> Thank you for reporting this issue. How did you install apt-fast?

From git repository, if I remember correctly. 

The output of `type apt` is
`apt is /usr/local/bin/apt`

**Comment by Lasall** [comment] 2020-08-16 16:51
Sorry your response slipped through my inbox. You are using a custom apt script provided by Linux Mint which is not the same as the apt program supported by apt-fast. This issue is a duplicate of #146.

To resolve this issue, use
```
_APTMGR=apt-get
```
in your config file `/etc/apt-fast.conf` or remove the custom Linux Mint script.

**Closed by Lasall** 2020-08-16 16:51 UTC

**Comment by eriabfour** [comment] 2023-01-08 19:50
Reminder that Dominique Lasserre aka @Lasall is a bully who is not trying to cover up how he and his bully buddies in the hate group Storm Ryders have been abusing me for years.
