### ISSUE TITLE
apt-fast clean error - (21: Is a directory)

### ISSUE THREAD

**Issue by t3chn0m4g3** [ilikenwf/apt-fast#162] opened 2019-04-04 06:41 UTC
Thank you for this great tool! We are currently testing it for our honeypot distribution [T-Pot](https://github.com/dtag-dev-sec/tpotce/) and as expected it reduces download time for packages significantly 🚀 

We ran into the following issue:
When running `apt-fast clean` we are getting the following error:
```
W: Problem unlinking the file apt-fast - pkgAcquire::Clean (21: Is a directory)
```

A quick look into `/var/cache/apt/archives/`unveils the `apt-fast` folder which is empty. Removing the folder with `rm -rf apt-fast` solves the error.

We are running Debian unstable and apt-fast 1.9.

**Comment by Lasall** [comment] 2019-04-04 11:14
Just change the DLDIR to `/var/cache/apt/apt-fast` . Possibly a duplicate of #100 .

**Comment by t3chn0m4g3** [comment] 2019-04-04 11:23
@Lasall Thank you for your quick response, will try ASAP!

**Comment by Lasall** [comment] 2019-04-04 11:38
That's a commented line, is there an (uncommented) DLDIR entry? If not can you:

    debconf-show apt-fast | grep aptcache

**Comment by t3chn0m4g3** [comment] 2019-04-04 12:44
Here the result ...

![image](https://user-images.githubusercontent.com/4318452/55556437-e02d2580-56e7-11e9-9a41-f7567b3df44f.png)

**Comment by Lasall** [comment] 2019-04-04 15:14
Did you install apt-fast by copying the scripts/config? Did you upgrade apt-fast from an older version? After deleting the folder `/var/cache/apt/archives/apt-fast` and doing some operations (like (re)installing a package) does this folder exist again?

**Comment by t3chn0m4g3** [comment] 2019-04-04 15:38
Installed via `/bin/bash -c "$(curl -sL https://git.io/vokNn)"` as a fresh install.
After deleting the folder it has not been recreated after multiple package installs / removals.

**Comment by t3chn0m4g3** [comment] 2019-04-06 09:22
Did a fresh install, left all the defaults untouched and it turns out, there are two `apt-fast` folders:
```
/var/cache/apt/apt-fast
/var/cache/apt/archives/apt-fast
```
After deleting the folders only `/var/cache/apt/archives/apt-fast` will be re-created and thus `apt-fast clean` showing `W: Problem unlinking the file apt-fast - pkgAcquire::Clean (21: Is a directory)`, while still leaving the defaults untouched.

Adjusting the defaults by uncommenting the lines accordingly in `/etc/apt-fast.conf`:
```
# Download temp folder for Downloadmanager
# example /tmp/apt-fast. Standard is /var/cache/apt-fast
#
# Default: /var/cache/apt/apt-fast
#
DLDIR=/var/cache/apt/apt-fast


# APT archives cache directory
#
# Default /var/cache/apt/archives
# (APT configuration items Dir::Cache and Dir::Cache::archives)
#
APTCACHE=/var/cache/apt/archives
```
... results in recreation of the folder on every package download install and `apt-fast clean` showing `W: Problem unlinking the file apt-fast - pkgAcquire::Clean (21: Is a directory)` again.

**Comment by t3chn0m4g3** [comment] 2019-04-09 10:13
Thoughts?

**Closed** 2019-04-09 11:37 UTC

**Comment by Lasall** [comment] 2019-04-09 11:40
Can you test with the recent commit after deleting config file and removing all apt-fast download folders?

I couldn't quite reproduce what you described but I think that might have been caused by not always cleaning up everything. But the default directory being in the archives/ folder was definitely a bug.

**Comment by t3chn0m4g3** [comment] 2019-04-09 11:55
Thank you. Will test ASAP and keep you posted!

**Comment by Lasall** [comment] 2019-04-09 12:00
Btw. this uses readlink which is included in coreutils since 8.23-1 (Sep '14), before that requires readlink package.

**Comment by t3chn0m4g3** [comment] 2019-04-09 12:05
Thanks for the heads-up :)

**Comment by t3chn0m4g3** [comment] 2019-04-09 12:47
Confirmed. Works perfectly fine now.

Thank you :bowtie:

**Comment by Lasall** [comment] 2019-04-09 12:52
Thanks a lot for discovering and figuring out the issue!

**Comment by denaturedBatToken** [comment] 2022-12-08 21:15
This is a reminder that Dominique Lasserre aka @Lasall is an abuser who is protecting his bully budies in the hate group Storm Ryders. You will receive these messages until I stop being bullies by @Lasall and his buddies or a better way to achieve that is made available.
