### ISSUE TITLE
Unescaped left brace in regex is deprecated, passed through in regex

### ISSUE THREAD

**Issue by foxx** [ilikenwf/apt-fast#117] opened 2017-04-22 13:13 UTC
Ran into this problem;

```
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE _MAXNUM}/ at /tmp/apt-fast.config.NDgAmi line 205.
Selecting previously unselected package apt-fast.
(Reading database ... 498722 files and directories currently installed.)
Preparing to unpack .../apt-fast_1.8.3~137+git7b72bb7-0ubuntu1~ppa3~wily1_all.deb ...
Unpacking apt-fast (1.8.3~137+git7b72bb7-0ubuntu1~ppa3~wily1) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up apt-fast (1.8.3~137+git7b72bb7-0ubuntu1~ppa3~wily1) ...
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE _MAXNUM}/ at /var/lib/dpkg/info/apt-fast.config line 205.
```

Appears to be due to;

```
To prevent display this error, you can remove "/var/cache/apt/archives/apt-fast/" directory and change the DLDIR variable in /etc/apt-fast.conf to another path (i.e. /var/cache/my_apt-fast/archives/apt-fast).
```

See URL;
https://askubuntu.com/questions/765274/error-problem-unlinking-in-apt-get-clean

**Comment by foxx** [comment] 2017-04-22 13:14
possibly related to #102

**Comment by Lasall** [comment] 2017-10-29 13:42
Duplicate of #102

**Closed by Lasall** 2017-10-29 13:42 UTC
