### ISSUE TITLE
No installing in 19.10

### ISSUE THREAD

**Issue by udipta** [ilikenwf/apt-fast#172] opened 2020-01-10 06:58 UTC
apt-fast : Depends: aria2 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

![Screenshot from 2020-01-10 12-26-14](https://user-images.githubusercontent.com/28093579/72132364-c15d6d00-33a4-11ea-81d1-eb258a341445.png)

**Comment by gothicVI** [comment] 2020-01-10 07:13
1. Add some information about your os.
2. This does not look like an apt-fast problem at all. The output clearly tells you that you're holding broken packages so this should be the first thing for you to fix.
3. Please do not post screenshots in the future but copy-paste the terminal output.
4. Some words describing your problem usually help people getting interested in helping you. Only posting an image without context and expecting support is a bald move.

**Comment by udipta** [comment] 2020-01-10 07:17
I am using ubuntu 19.10 and the steps I followed are :

**Comment by gothicVI** [comment] 2020-01-10 09:08
The steps so far are correct.
However, if you look at point 2 of my former reply, your issue does not seem to be apt-fast related. Please post the output of `sudo apt update` and `sudo apt dist-upgrade`. If there are errors in these, you'll need to fix them first.

**Comment by udipta** [comment] 2020-01-10 10:06
sudo apt-fast update
Command not found: aria2c
You must configure /etc/apt-fast.conf to use aria2c or another supported download manager

**Comment by gothicVI** [comment] 2020-01-10 10:18
Do you read what I write? `sudo apt update` and `sudo apt dist-upgrade`. There's no `-fast` in here...

**Comment by udipta** [comment] 2020-01-10 10:19
i did that buddy. no error there

**Comment by guekho64** [comment] 2020-01-11 01:39
I've got the feeling that either Ubuntu's apt servers have been messed up (somehow...), or @udipta 's computer has some severe problems, affecting `apt`... (?)

No matter what the cause is, you could always try one of these:

* [Quick Installation](https://github.com/ilikenwf/apt-fast#quick-install)
* [Manual Installation](https://github.com/ilikenwf/apt-fast#manual)

Also, if `apt` won't let you install `aria2c` by any means, you can try to manually compile and install it, or download a ready-to-use binary:

* [Official Source Code](https://github.com/aria2/aria2/releases)
* [Community-made Binaries](https://github.com/q3aql/aria2-static-builds/releases)

If none of these methods work, or you don't want to go through any of them, then further analysis should be done to your specific situation, as It seems to be quite weird, specially after seeing how `apt` refuses to install any of the packages you tried...

Maybe a last resort option could be to execute `sudo apt-get --purge autoremove -y --force-yes` to try to completely remove as much packages as possible which are considered useless by `apt`, like orphaned packages, assuming `apt` it's still on a working state, or `sudo apt-get install -f -y --force-yes` to try to recover `apt` after falling into an errored state...

Just an advice: Proceed with caution, as these commands are potentially dangerous if used incorrectly; Read carefully, and cancel the operation if feeling insecure!

**Comment by gothicVI** [comment] 2020-01-11 08:57
> i did that buddy. no error there

Did you also read what I linked you? Did you, e.g., check via synaptic for errors?
The installation error clearly states that your package manager somehow is borked so you'll have to fix that first.
@guekho64 Surely it's the latter of your assumptions. Given that your suggestions most likely won't work or make the issue worse.

**Comment by guekho64** [comment] 2020-01-11 18:30
I've dealt with these kind of problems on my own before, and personally I don't find 'em hard to fix, although I need to recall each and every step done before the error appeared...

The problem here, in my opinion, it's the lack of information about the issue affecting @udipta.

More information must be provided in order to attempt to fix the problem, including log files, simple text, screenshots (I'm OK with them), etc.

In my personal experience, this problem it's quite ambiguous, as it can appear from a wide range of other issues on your computer, ranging from a bad configuration in `/etc/apt/` directory (or any of its files), to a Hard Disk issue, where a bad sector on the disk has been discovered, and _that_ specific sector has one or more files related to `apt`, which also unfolds into a wide range of other problems...

In the best of scenarios, the problem itself will fix over time with no intervention at all.

_Just as a sidenote, if you ever need to post a screenshot, I'd recommend doing so this way_:

<details><summary><i>Your Image</i></summary>

![image](https://user-images.githubusercontent.com/8020999/72208857-a7d42800-346d-11ea-90ea-1fd35b95eb83.png)

</details>

_That way you don't occupy too much space!_

Here's the code to do so:
``` html
<details><summary><i>Your title</i></summary>

Whatever you need to post within this spoiler

</details>
```

**Comment by guekho64** [comment] 2020-01-11 19:34
@udipta Now I recall what the problem is: If I recall correctly, Ubuntu **_does not_** include some `apt` repositories needed to install `aria2c`. such as "multiverse" and "universe".

To enable such repositories, follow these steps:

<details><summary>Steps</summary>

* Go into `/etc/apt/' directory, and rename "sources.list" to "sources.list.bck"
* Create a new file called "sources.list"
* Copy & paste this

<details><summary><b><i>sources.list</i></b></summary><pre>

deb http://archive.ubuntu.com/ubuntu eoan main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu eoan-updates main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu eoan-backports main restricted universe multiverse

deb http://security.ubuntu.com/ubuntu/ eoan-security main restricted universe multiverse
deb http://archive.canonical.com/ubuntu/ eoan partner

</pre></details>

* Save the file
* Issue a `sudo apt update`
* Try installing `aria2` once more

</details>

<details><summary>Commands for Ubuntu</summary>

``` sh
sudo mv "/etc/apt/sources.list" "/etc/apt/sources.list.bck"; \
sudo touch "/etc/apt/sources.txt"; \
sudo xdg-open "/etc/apt/sources.txt"; \
sudo mv "/etc/sources.txt" "sources.list"; \
sudo apt update; \
sudo apt install aria2;
```

</details>

In case of failure, or if you simply want to undo the changes, you can easily go back by deleting the new `sources.list` and renaming back the old `sources.list.bck` to its real name.

<details><summary>Undo Commands for Ubuntu</summary>

``` sh
sudo rm "/etc/apt/sources.list"
sudo mv "/etc/apt/sources.list.bck" "/etc/apt/sources.list"
```

</details>

**Comment by Lasall** [comment] 2020-04-06 21:29
I'm closing this issue. I think guekho64 covered it pretty well with the universe source inclusion. If this issue still exists, please feel free to reopen. Thank you for reporting and all participation!

**Closed by Lasall** 2020-04-06 21:29 UTC

**Comment by RydrIsAnAbuseClub** [comment] 2022-12-11 20:27
This is another reminder that Dominique Lasserre aka @Lasall is an abuser who along with his buddies in the hate group Stom Ryders has been bullying me for years. Dominique is currently trying to cover this up. DO NOT let @Lasall get away with abuse.

**Comment by noexcuse4u** [comment] 2023-02-06 21:06
Reminder that Dominique Lasserre aka @Lasall is an abuser who has been bullying me for years together with his buddies in the hate group Storm Ryders and is now trying to cover that up.
