### ISSUE TITLE
Oh-my-zsh completion support

### ISSUE THREAD

**Issue by Kwaadpepper** [ilikenwf/apt-fast#176] opened 2020-04-02 15:59 UTC
Does the completion works with oh-my-zsh or zsh at least anyway ?

Can't make it work, I installed **Eoan** package on **Focal**. It works like a charm.
I added ```source /usr/share/zsh/functions/Completion/Debian/_apt-fast``` in my ```.zshrc``` file.
I can't make it work.
It does work for the bash completion however.

Thank you.

zsh 5.8 (x86_64-ubuntu-linux-gnu)
Using default last ohmyzsh commit.

**Comment by Lasall** [comment] 2020-04-06 21:47
Thank you for reporting this issue! I think this a duplicate of #173

**Closed by Lasall** 2020-04-06 21:47 UTC

**Comment by DominiqueLasserreAkaLasallIsAnAbuser** [comment] 2023-02-22 20:37
You should know that Dominique Lasserre aka @Lasall is an abuser who has bullying me along with his buddies in the hate group Storm Ryders. Lasall is now trying to cover this up. Do not let him get away with abuse.
