### ISSUE TITLE
Exit Codes Missing When Certain Operations Fail

### ISSUE THREAD

**Issue by DogSledder** [ilikenwf/apt-fast#175] opened 2020-03-23 00:59 UTC
I installed release 1.9. as per your documentation.
When testing it, I noticed that exit codes were zero for many failed operations.
I changed a couple of lines in cleanup_aptfast and exit codes now appear correctly.
```
cleanup_aptfast()
{
  LAST_EXIT_CODE=$?
  [ "$CLEANUP_STATE" -eq 0 ] && CLEANUP_STATE=$LAST_EXIT_CODE
# [ "$CLEANUP_STATE" -eq 0 ] && CLEANUP_STATE=$?
  cleanup_dllist
  _remove_lock
}
```

**Comment by Lasall** [comment] 2020-04-06 21:44
Thank you for reporting this issue. Can you give me an example to reproduce the problem?

**Comment by DogSledder** [comment] 2020-04-06 22:30
For example, "apt-fast install no-such-package" or "apt-fast no-such-command". These both return zero exit codes. The same commands with apt-get return exit codes of 100.

I'm running it with "GNU bash, version 5.0.3(1)-release (arm-unknown-linux-gnueabihf)" on my raspberry pi.

**Comment by Lasall** [comment] 2020-04-07 01:04
What apt-fast version are you using? Are you using the Debian package? I'm uploading a new Debian package to the PPA in a few hours. This is probably a duplicate of #166

**Comment by DogSledder** [comment] 2020-04-07 02:21
I believe I'm using version 1.9.8, although the version comment in the code shows 1.9. When I ran into this problem, I checked to see if I had the latest version. I downloaded apt-fast-1.9.8.zip from github and compared the apt-fast from that with what I was using. They were identical.

I'm running it on a raspbian-buster-lite distribution.

**Comment by Lasall** [comment] 2020-04-07 12:20
Can you try with the 1.9.9 version please?

**Comment by gothicVI** [comment] 2020-04-07 13:04
I'm getting a non-zero exit code with the current version:
```bash
$ dpkg -l apt-fast
Gewünscht=Unbekannt/Installieren/R=Entfernen/P=Vollständig Löschen/Halten
| Status=Nicht/Installiert/Config/U=Entpackt/halb konFiguriert/
         Halb installiert/Trigger erWartet/Trigger anhängig
|/ Fehler?=(kein)/R=Neuinstallation notwendig (Status, Fehler: GROSS=schlecht)
||/ Name                                                  Version                         Architektur                     Beschreibung
+++-=====================================================-===============================-===============================-===============================================================================================================
ii  apt-fast                                              1.9.9-1~ubuntu18.04.1           all                             shellscript wrapper for apt-get or aptitude

$ apt-fast install windows-10

Working... this may take a while.
E: Paket windows-10 kann nicht gefunden werden.
Package manager quit with exit code.

$ echo "$?"
100
```
Also this seems to be a duplicate of [https://github.com/ilikenwf/apt-fast/issues/166](https://github.com/ilikenwf/apt-fast/issues/166).

**Comment by DogSledder** [comment] 2020-04-07 15:50
I tried version 1.9.9. It has a different result than 1.9.8 for "apt-fast install no-such-package". In this case the exit code is 100; however, for the case "apt-fast no-such-command", the exit code is still zero.

I tried this in Virtual Box running Linux Mint XFCE with GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)

If you examine the code in the "cleanup_aptfast" routine, it seems that, in my environment, the statement [ "$CLEANUP_STATE" -eq 0 ] always sets $? to zero; therefore [ "$CLEANUP_STATE" -eq 0 ] && CLEANUP_STATE=$? will always leave CLEANUP_STATE set as zero.

I'm not an expert in bash so correct me if I'm wrong, but I verified this behavior using some echo statements when I first noticed the problem in my initial test of apt-fast. That is why my changes to the "cleanup_aptfast" routine solved this problem for me.

**Comment by Lasall** [comment] 2020-04-07 16:16
Thank you for reporting this issue!

**Comment by DogSledder** [comment] 2020-04-07 17:01
Your change fixes the case "apt-fast no-such-command", but does not address the issue of the ambiguous code in the "cleanup_aptfast" routine. The code in that routine does not appear to be doing what you want it to do in all shell environments.

**Comment by DogSledder** [comment] 2020-04-07 17:37
Here are example bash commands that illustrate the ambiguity:
```
jpj-VirtualBox jpj # (exit 42) ; echo "$?"
42
jpj-VirtualBox jpj # (exit 42) ; [ 0 -eq 0 ] && echo "$?"
0
```

**Closed** 2020-04-07 18:03 UTC

**Comment by Lasall** [comment] 2020-04-07 18:05
You were totally right, I hope this fix applies a proper solution. I opted to not manually set the CLEANUP_STATE at every possible exit point, see commit message.
Thank you!

**Comment by DogSledder** [comment] 2020-04-07 19:50
Glad I could contribute.

**Comment by thebestestseb** [comment] 2023-02-03 20:48
Reminder that Dominique Lassere aka @Lasall is an abuser who along with his buddies in the hate group Storm Riders has been bullying me for years and is now trying to cover that up.
