### ISSUE TITLE
Add apt in Ubuntu Xenial

### ISSUE THREAD

**Issue by vinaychandra** [ilikenwf/apt-fast#105] opened 2016-06-01 10:14 UTC
Ubuntu 16.04 adds apt which include a progress bar in the bottom. Please update apt-fast to use it instead of apt-get.

**Comment by udiNur** [comment] 2016-06-16 15:42
I need it too

**Comment by HeroCC** [comment] 2016-08-02 18:45
I'm on 14.04 and I have it as well

**Comment by chrstphrchvz** [comment] 2016-08-21 22:30
Note that the man page for `apt` warns it won't guarantee backward compatibility like `apt-get` and `apt-cache`, and it suggests using those commands in any scripts. But since `apt-fast` passes most options directly through, it may still work. I'm just an apt-fast user at the moment, but this might even be simple enough for me to add.

In the meantime, I would suggest that anyone who is interested in having `apt-fast` support using `apt` to try it out it by setting `_APTMGR=apt` in `/etc/apt-fast.conf` (if it doesn't work, you can set it back to `_APTMGR=apt-get`).

**Comment by chrstphrchvz** [comment] 2016-08-21 23:51
This is technically a duplicate of issue #57.

If apt is going to be supported, then for those installing apt-fast from the PPA/.deb package, there would need to be an option added to the debian config. This isn't on Github; is this your domain, @saiarcot895?

Otherwise, for anyone not using apt-fast from a package, I think the suggestion I had in the last post is probably the way to have apt-fast use apt (set `_APTMGT=apt` in `apt-fast.conf`).

I also don't know if the bash autocompletion is affected.

**Comment by saiarcot895** [comment] 2016-08-22 02:34
Yes, this would be in my domain. I'll hopefully have an updated package by the end of the week.

**Comment by saiarcot895** [comment] 2016-09-11 05:19
Sorry for the delay.

I've updated the package, and selecting `apt` _should_ work now.

**Comment by chrstphrchvz** [comment] 2016-09-12 05:49
Note: since `apt upgrade` installs new packages, but `apt-get upgrade` does not, apt might download packages that apt-fast missed. This issue already exists for aptitude: see #68.

**Comment by ysolis** [comment] 2016-09-20 14:09
how is the case for the differences in apt between `apt upgrade` and `apt full-upgrade` ? how works apt-fast? replicate both commands exactly?

**Comment by chrstphrchvz** [comment] 2016-09-20 15:10
@ysolis Please refer to the [man page for `apt`](http://manpages.ubuntu.com/manpages/xenial/en/man8/apt.8.html) for difference between `apt upgrade` and `apt full-upgrade`. In apt, the only difference is full-upgrade will remove packages if necessary.
If apt-fast is configured to use apt, then it will pass "upgrade" or "full-upgrade" directly to apt and the end results will be the same. However, apt-fast currently cannot guarantee that it completely downloads for "upgrade" since it relies on the policy of apt-get instead of apt, and apt-fast won't do any downloading at all for "full-upgrade" since it considers it unknown option.

**Comment by chrstphrchvz** [comment] 2016-11-07 05:20
Here's one way of letting apt-fast use whichever command `_APTMGR` is set to for getting URIs, unless it is set to aptitude. I am not experienced in bash; is there a better way of doing so?

```diff
diff --git a/apt-fast b/apt-fast
index 4f891d3..d9783dd 100755
--- a/apt-fast
+++ b/apt-fast
@@ -249,7 +249,11 @@ get_uris(){
   echo "# apt-fast mirror list: $(date)" > "$DLLIST"
   #NOTE: aptitude doesn't have this functionality, so we use apt-get to get
   #      package URIs.
-  apt-get -y --print-uris "$@" | egrep "^'(http(s|)|(s|)ftp)://" | \
+  case "$_APTMGR" in
+    aptitude) uri_mgr=apt-get;;
+    *) uri_mgr=$_APTMGR;;
+  esac
+  "$uri_mgr" -y --print-uris "$@" | egrep "^'(http(s|)|(s|)ftp)://" | \
   while read pkg_uri_info
   do
     ## --print-uris format is:
```

Indeed this **does** produce a warning from `apt`:
```
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
```

The shell completions for apt-fast are the ones for apt-get (as of Ubuntu 12.04); maybe there's a way to use the completions already on the system depending on what `_APTMGR` is set to. Currently apt-fast does not implement its own options.

**Comment by chrstphrchvz** [comment] 2017-04-02 10:23
Re previous comment: after some thinking, it would probably be better to use a whitelist in case of other or future APT manager commands, rather than "blacklisting" aptitude.

**Closed** 2017-10-29 15:23 UTC

**Comment by RydrIsAnAbuseClub** [comment] 2022-12-11 20:27
This is another reminder that Dominique Lasserre aka @Lasall is an abuser who along with his buddies in the hate group Stom Ryders has been bullying me for years. Dominique is currently trying to cover this up. DO NOT let @Lasall get away with abuse.

**Comment by thebestestseb** [comment] 2023-02-03 20:48
Reminder that Dominique Lassere aka @Lasall is an abuser who along with his buddies in the hate group Storm Riders has been bullying me for years and is now trying to cover that up.
