### ISSUE TITLE
Problem with checksums. Aria2 is unhappy.

### ISSUE THREAD

**Issue by Cediddi** [ilikenwf/apt-fast#150] opened 2018-08-11 15:30 UTC
Hi, I tried to run apt-fast update today. I'm using Linux Mint 17.3 (14.04). Today apt-fast gave me error. so I checked the apt-fast.list file and found out that google package has a problem with md5 checksums.

Here's the apt-fast.list entry:

    http://packages.cloud.google.com/apt/pool/google-cloud-sdk_211.0.0-0_all_defe6ba217a03a61d29d2089c5b64929bf923b6a0ce2d4400830d5124faa55d2.deb
     checksum=md5=
     out=google-cloud-sdk_211.0.0-0_all.deb

Here's the error that's visible on apt-fast

    Exception caught
    Exception: [AbstractOptionHandler.cc:69] errorCode=28 We encountered a problem while processing the option '--checksum'.
      -> [OptionHandlerImpl.cc:395] errorCode=1 Unrecognized checksum

And here's the possibly related apt-cache show output:

    Package: google-cloud-sdk
    Version: 211.0.0-0
    Installed-Size: 133956
    Maintainer: Google Cloud SDK Authors <https://code.google.com/p/google-cloud-sdk/>
    Architecture: all
    Depends: python2.7
    Recommends: python-crcmod
    Suggests: google-cloud-sdk-app-engine-java, google-cloud-sdk-app-engine-python, google-cloud-sdk-pubsub-emulator, google-cloud-sdk-bigtable-emulator, google-cloud-sdk-datastore-emulator, kubectl
    Conflicts: gsutil
    Description: Utilities for the Google Cloud Platform
    Description-md5: b28c3a146cdbaea19fb2ce8a00cccd4b
    Homepage: https://cloud.google.com/sdk/
    Filename: pool/google-cloud-sdk_211.0.0-0_all_defe6ba217a03a61d29d2089c5b64929bf923b6a0ce2d4400830d5124faa55d2.deb
    Priority: optional
    SHA256: defe6ba217a03a61d29d2089c5b64929bf923b6a0ce2d4400830d5124faa55d2
    Section: misc
    Size: 19158400

How can I help you solve this issue? I'm more of a python guy, my bash skills are weak.

Edit:
After I hold the google-cloud-sdk package, apt-fast works the same again. This verifies the issue.

**Comment by Lasall** [comment] 2019-02-24 14:20
Duplicate of #114

**Closed by Lasall** 2019-02-24 14:20 UTC
