### ISSUE TITLE
Installing the newest apt-fast from the ppa doesn't work

### ISSUE THREAD

**Issue by HybridDog** [ilikenwf/apt-fast#135] opened 2018-01-09 08:15 UTC
When I try to install apt-fast using `sudo apt install apt-fast`, I get an error message:
`Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/\${ <-- HERE _MAXNUM}/ at /tmp/apt-fast.config.ifENXR line 212.`

Here's the whole output:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Suggested packages:
  aptitude
The following NEW packages will be installed:
  apt-fast
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/34.5 kB of archives.
After this operation, 120 kB of additional disk space will be used.
Preconfiguring packages ...
Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/\${ <-- HERE _MAXNUM}/ at /tmp/apt-fast.config.mXtxxl line 212.
apt-fast failed to preconfigure, with exit status 255
Selecting previously unselected package apt-fast.
(Reading database ... 442984 files and directories currently installed.)
Preparing to unpack .../apt-fast_1.8.3~144+git3a6bd77-0ubuntu1~ppa4_all.deb ...
Unpacking apt-fast (1.8.3~144+git3a6bd77-0ubuntu1~ppa4) ...
Processing triggers for man-db (2.7.6.1-2) ...
Setting up apt-fast (1.8.3~144+git3a6bd77-0ubuntu1~ppa4) ...
Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/\${ <-- HERE _MAXNUM}/ at /var/lib/dpkg/info/apt-fast.config line 212.
dpkg: error processing package apt-fast (--configure):
 subprocess installed post-installation script returned error exit status 255
Errors were encountered while processing:
 apt-fast
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
I'm using lubuntu 17.10.

**Comment by Lasall** [comment] 2018-01-09 19:33
Thank you for your bug report. You are using an outdated package of apt-fast.
To fix the installation issue you can edit `/var/lib/dpkg/info/apt-fast.config` in line 212 and insert a `\` before the opening curly bracket.

I recommend to change PPA to apt-fast/stable to get the newest apt-fast.

**Comment by Lasall** [comment] 2018-01-09 19:35
Also duplicate of #102

**Comment by Lasall** [comment] 2018-01-16 20:29
Closing due to inactivity and since this is a duplicate.

**Closed by Lasall** 2018-01-16 20:29 UTC

**Comment by Lasall** [comment] 2018-01-16 20:31
Closing due to inactivity and since this is a duplicate. Please reopen if you need further assistance.

**Comment by HybridDog** [comment] 2018-01-20 16:15
It's a duplicate, I forgot to search in close issues I think, sorry.
